### PR TITLE
Feat: ZKEVM Support

### PR DESCRIPTION
**Pull request by timjrobinson**
Added support for Polygon zkEVM chain.

Tested locally with https://github.com/balancer/frontend-v2/pull/3378 and it appears to be working

### CODE REVIEW

**Comment by franzns** [comment]
As discussed, we are going to wait with this until the subgraphs are ready

**Comment by timjrobinson** [comment]
This is good to go except for the smart contract deployed for `poolDataQueryContract`. 

We don't need the subgraphs yet as we're not going to have gauges for zkEVM on deployment and the APR's are being pulled from the Balancer API ATM (which doesn't need a blocks subgraph). I've removed the jobs related to staking.

**Comment by franzns** [comment]
This won't work on other chains now as the ABI changed for the query helper contract. Can you adapt those configs as well? 

To be sure: You tested all the crons and none of them needs a blocks subgraph?

**Comment by timjrobinson** [comment]
@franzns I've removed all crons that require the blocks subgraph and this is all working locally now with the new pool data contract. I've rebased it on #370 so that one can be merged first then this one.

**Pull request merged**
