### PR TITLE
Add chains array param to user balance query

### PR DESCRIPTION
**Pull request by danielmkm**
Add support for fetching user balances from multiple chains at once. As the balances leverage the token prices, we also implement support for multi chain token price fetching.

### CODE REVIEW

**Comment by danielmkm** [comment]
~TODO: need to add support for fetching prices for multiple chains~

**Review by gmbronco — APPROVED** [review]
lgtm – i just added a small change making it default to all chains if no chains are provided and an address filter, might be slightly easier to query.

**Comment by danielmkm** [comment]
> lgtm – i just added a small change making it default to all chains if no chains are provided and an address filter, might be slightly easier to query.

Thanks for having a look @gmbronco. The way you did `allChains` will include fantom and optimism for balancer. You'd want to scope it to the project.

**Comment by gmbronco** [comment]
we changed the default fallback to the chainId passed in the header, so it's backwards compatibile.

**Pull request merged**
